package me.checkium.vhackapi;

public enum Stats {

    MONEY, IP, INET, HDD, CPU, RAM, FW, AV, SDK, IPSP, SPAM, SCAN, ADW, NETCOINS, BONUS, ELO, HASH, ID, UHASH, SCORE, BOOST, CLUSTER_ID, POSITION, RANK, ACTSPYWARE

}
